Improve print function

diff --git a/bdry b/bdry
--- a/bdry
+++ b/bdry
@@ -1,8 +1,8 @@
 #!/bin/bash
 # Adds specified information into a time-formatted diary entry
 
-source ./settings
-source ./template
+source settings
+source template
 if [ ! -d "$main_folder" ] ; then
     mkdir "$main_folder"
 fi
@@ -71,14 +71,27 @@ case $1 in
         exit 0
         ;;
     -p | -print )
-        if [ -f "$(find "$main_folder" -name "$3")" ]; then
-            today="$(find "$main_folder" -name "$3")"
+        shift;
+        output="cat"
+
+        if [[ "$1" =~ [n|num|number] ]]; then
+            output="cat -n"
+            shift;
         fi
-        if [ "$2" = "number" ] || [ "$2" = "num" ] || [ "$2" = "n" ]; then
-            cat -n "$today"
-            exit 0
+        # Expand @shortcuts if present in settings
+        if [ "${1:0:1}" == "@" ] ; then
+            day="${shortcuts["${1:1}"]}"
+            today="$(find "$main_folder" -name "$day")"
+        # If not a shortcut, but also not an empty variable (i.e. a date is given)
+        elif [ -n "$1" ] ; then
+            today="$1"
         fi
-        cat "$today"
+        # If the file does not exist
+        if [ ! -f "$today" ]; then
+            echo "File \"$today$day\" not found"
+            exit 1
+        fi
+        $output "$today"
         exit 0
         ;;
     -e | -edit ) 
@@ -103,18 +116,13 @@ case $1 in
         echo "(edited file at $(date +%T))" >> "$today"
         exit 0
         ;;
-    -s | -setup )
+    -s | -search )
         shift;
-        if [ $# -gt 1 ]; then
-            echo "Set one folder to store entries." >&2
-            exit 1
-        fi
-        if [ ! -d "$1" ]; then
-            echo "Directory does not exist." >&2
-            exit 1
-        fi
-        # Set main folder
-        sed -i 3s/.*/export\ main_folder="$1"/ ./settings
+        grep -r \
+        "$(if [ "$1" == "c" ]; then 
+            echo -c 
+        fi)"
+        "$@" "$main_folder"
         exit 0
         ;;
     * )
